name: Actualizar Portal

on:
  push:
    paths:
      - 'data/**'
      - 'portal/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Commit if needed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto: actualizar" || echo "Sin cambios"
          git push || echo "Sin cambios"